# Generated by Django 3.2.5 on 2021-07-30 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20210730_1454"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bid",
            options={
                "ordering": ["-bid_amount"],
                "verbose_name": "Bid",
                "verbose_name_plural": "Bids",
            },
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="init_bid",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="initial bid amount in USD"
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="auction_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="core.auctionitem",
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="bid_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                verbose_name="bid amount made by the person in USD",
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="bidder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="funds",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="current funds on the account in USD",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="max_auto_bid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="maximum bid amount in USD when auto-bidding is turned on on the item",
                max_digits=8,
                verbose_name="max bid amount in USD",
            ),
        ),
    ]
