# Generated by Django 3.2.5 on 2021-07-31 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bid",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
