# Generated by Django 3.2.5 on 2021-07-31 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210731_1841'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('auction_item', 'bidder')},
        ),
    ]
