# Generated by Django 3.2.5 on 2021-08-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_auctionitem_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auctionitem",
            options={
                "ordering": ["-created_date", "title", "description"],
                "verbose_name": "Auction item",
                "verbose_name_plural": "Auction items",
            },
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="compressed_picture",
            field=models.ImageField(
                blank=True,
                upload_to="auction_items/",
                verbose_name="item compressed picture",
            ),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="picture",
            field=models.ImageField(
                upload_to="auction_items/", verbose_name="item picture"
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="bid_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="bid amount in USD"
            ),
        ),
    ]
