# Generated by Django 3.2.5 on 2021-08-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_auto_20210802_0907"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionitem",
            name="init_bid",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                verbose_name="initial bid amount in USD",
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="bid_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="bid amount in USD"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="funds",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="current funds on the account in USD",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="max_auto_bid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="maximum bid amount in USD when auto-bidding is turned on on the item",
                max_digits=10,
                verbose_name="max bid amount in USD",
            ),
        ),
    ]
